const fruits = [
  "Apple",
  "Avocado",
  "Coconut",
  "Almond",
  "Alpine Strawberry",
  "African Cherry",
  "Acai",
  "Abiu",
  "Abiurana",
  "Ackee",
  "Annatto",
  "Acerola",
  "Alligator Apple",
  "Mango",
  "Banana",
  "Orange",
  "Appricot",
  "Pomogranate",
  "Guvava",
  "Blackberry",
  "Cherry",
  "Sapota",
  "Custured Apple",
  "Pineapple",
  "Lemon",
  "Watermelon",
  "Strawberry",
  "Kiwi",
  "Papaya",
  "Peach",
  "Grapes",
  "Eclair",
  "Honeycomb",
  "Jellybean",
  "Raspberries",
  "Rose Apple",
  "Rangpur Lime",
  "Rambutan",
  "kakadu Plum",
  "Jack Fruit",
  "Date",
  "Drew Berry",
  "Dragon Fruit",
  "Fig",
  "Ice Apple",
  "Nuts",
  "Naranja",
  "Noda Plum",
  "Olives",
  "Opal Apple",
  "Passion Fruit",
  "Pacific Rose Apple",
  "Quararibea Cordata Fruit",
  "Queen Anne Cherries",
  "tangerine",
  "Vanilla",
  "Wax Gourd",
  "Wine Berry",
  "Yellow Grape",
  "Yali Pear",
];

module.exports = fruits;
